In [49]:
#Importing the required libraries

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
import numpy as np

In [50]:
#Loading the IRIS dataset

from sklearn.datasets import load_iris

iris = load_iris(as_frame=True)

_Exploring the Dataset_

In [51]:
iris.data

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [52]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [53]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [66]:

X = iris.data
#Setting the target variable to 1 for "virginica" and 0 for "not virginica
y = (iris.target_names[iris.target] == "virginica").astype(int)

In [67]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [55]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [68]:
logreg_model = LogisticRegression(random_state=0)
logreg_model.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [69]:
y_pred = logreg_model.predict(X_test)

In [73]:
y_test_prob = log_reg.predict_proba(X_test)
y_test_prob

array([[8.83624770e-02, 9.11637523e-01],
       [9.65799050e-01, 3.42009502e-02],
       [9.99996911e-01, 3.08886977e-06],
       [1.87768543e-02, 9.81223146e-01],
       [9.99993834e-01, 6.16570567e-06],
       [9.41519187e-03, 9.90584808e-01],
       [9.99995734e-01, 4.26586327e-06],
       [7.15482253e-01, 2.84517747e-01],
       [6.81946171e-01, 3.18053829e-01],
       [9.51456906e-01, 4.85430936e-02],
       [1.66779004e-01, 8.33220996e-01],
       [8.08083228e-01, 1.91916772e-01],
       [7.86651279e-01, 2.13348721e-01],
       [7.36827436e-01, 2.63172564e-01],
       [7.16602924e-01, 2.83397076e-01],
       [9.99996395e-01, 3.60524566e-06],
       [7.74779969e-01, 2.25220031e-01],
       [8.70701373e-01, 1.29298627e-01],
       [9.99992899e-01, 7.10108414e-06],
       [9.99995875e-01, 4.12523363e-06],
       [2.68263048e-01, 7.31736952e-01],
       [7.67365756e-01, 2.32634244e-01],
       [9.99981199e-01, 1.88005180e-05],
       [9.99993488e-01, 6.51233093e-06],
       [4.514705

In [74]:
y_test_prob[:,1]

array([9.11637523e-01, 3.42009502e-02, 3.08886977e-06, 9.81223146e-01,
       6.16570567e-06, 9.90584808e-01, 4.26586327e-06, 2.84517747e-01,
       3.18053829e-01, 4.85430936e-02, 8.33220996e-01, 1.91916772e-01,
       2.13348721e-01, 2.63172564e-01, 2.83397076e-01, 3.60524566e-06,
       2.25220031e-01, 1.29298627e-01, 7.10108414e-06, 4.12523363e-06,
       7.31736952e-01, 2.32634244e-01, 1.88005180e-05, 6.51233093e-06,
       5.48529422e-01, 1.61387534e-06, 2.28618557e-05, 9.70304322e-02,
       6.33731379e-03, 1.22395786e-05])

_Logistic Regression Model Evaluation_

In [75]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[24  0]
 [ 0  6]]


As can be seen from confusion matrix, there are no FP (False Positive) and no FN (False Negative).  

In [77]:
from sklearn.metrics import precision_score, recall_score, f1_score

precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Precision: 1.0
Recall: 1.0
F1 Score: 1.0
