In [1]:
#Importing libraries
import sys
import torch
import helpers as h

In [2]:
# check the version of Python and PyTorch
h.print_python_version()
h.print_pytorch_version()

Python version: 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]
pyTorch version: 2.0.0+cpu


__Using PyTorch__

In [8]:
#Creating 2 vectors of length 3 using PyTorch
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])
h.print_tensor_info(x)
h.print_tensor_info(y)

tensor([1, 2, 3])
Type         <class 'torch.Tensor'>
dtype        torch.int64
Dimension    1
Shape        (3,)
tensor([9, 8, 7])
Type         <class 'torch.Tensor'>
dtype        torch.int64
Dimension    1
Shape        (3,)


In [9]:
#Calculating dot product of 2 vectors
dot_product_torch = x.dot(y)
print(dot_product_torch)

tensor(46)


In [10]:
#Creating 2 matrices (2x2) using PyTorch

d1 = torch.tensor([[1, 2],[4,6] ])
d2 = torch.tensor([[9, 8],[7, 6] ])
h.print_tensor_info(d1)
h.print_tensor_info(d2)

tensor([[1, 2],
        [4, 6]])
Type         <class 'torch.Tensor'>
dtype        torch.int64
Dimension    2
Shape        (2, 2)
tensor([[9, 8],
        [7, 6]])
Type         <class 'torch.Tensor'>
dtype        torch.int64
Dimension    2
Shape        (2, 2)


In [11]:
#Performing matrix multiplication
mat_mult_torch = torch.matmul(d1,d2)
print(mat_mult_torch)

tensor([[23, 20],
        [78, 68]])


__Using Tensorflow__

In [1]:
#Importing libraries
import tensorflow as tf
import numpy as np

In [2]:
#Creating 2 vectors of length 3 using TensorFlow
t1 = tf.constant([1,2,3])
t2 = tf.constant([9,8,7])
print(t1)
print(t2)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([9 8 7], shape=(3,), dtype=int32)


In [3]:
#Calculating dot product of 2 vectors
dot_product = tf.tensordot(t1,t2, axes=1)
print(dot_product)

tf.Tensor(46, shape=(), dtype=int32)


In [4]:
#Creating 2 matrices (2x2) using TensorFlow
td1 = tf.constant([[1,2],[4,6]])
td2 = tf.constant([[9,8],[7,6]])
print(td1)
print(td2)

tf.Tensor(
[[1 2]
 [4 6]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[9 8]
 [7 6]], shape=(2, 2), dtype=int32)


In [5]:
#Performing matrix multiplication
mat_mult = tf.matmul(td1,td2)
print(mat_mult)

tf.Tensor(
[[23 20]
 [78 68]], shape=(2, 2), dtype=int32)
